ALTER TABLE contact_types ALTER COLUMN "type" TYPE VARCHAR(10);

ALTER TABLE contacts ALTER COLUMN first_name TYPE VARCHAR(20);
ALTER TABLE contacts ALTER COLUMN last_name TYPE VARCHAR(20);
ALTER TABLE contacts ALTER COLUMN address TYPE VARCHAR(30);
ALTER TABLE contacts ALTER COLUMN phone_number TYPE VARCHAR(15);

ALTER TABLE roles ALTER COLUMN role_name TYPE VARCHAR(20);

ALTER TABLE users ALTER COLUMN email TYPE VARCHAR(30);
ALTER TABLE users ALTER COLUMN password TYPE VARCHAR(150);
ALTER TABLE users ALTER COLUMN first_name TYPE VARCHAR(20);
ALTER TABLE users ALTER COLUMN last_name TYPE VARCHAR(20);