ALTER TABLE contact_types ALTER COLUMN "id" TYPE BIGINT;
ALTER TABLE contacts ALTER COLUMN id TYPE BIGINT;
ALTER TABLE roles ALTER COLUMN id TYPE BIGINT;
ALTER TABLE users ALTER COLUMN id TYPE BIGINT;

ALTER TABLE user_roles ALTER COLUMN role_id TYPE BIGINT;
ALTER TABLE user_roles ALTER COLUMN user_id TYPE BIGINT;

ALTER TABLE contacts ALTER COLUMN app_user_id TYPE BIGINT;
ALTER TABLE contacts ALTER COLUMN contact_type_id TYPE BIGINT;